<a href="https://colab.research.google.com/github/shubh9956/Deep-Learning/blob/main/Word_embedding_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''here I have imported the important libraries in keras and numpy and then 
I'm going to do the food review classification I have like 10 reviews here very simple data set and then 10 labels
so the first five are positive reviews you can figure it out and the next five are negative reviews'''

"here I have imported the important libraries in keras and numpy and then \nI'm going to do the food review classification I have like 10 reviews here very simple data set and then 10 labels\nso the first five are positive reviews you can figure it out and the next five are negative reviews"

In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [ ]:
'''so the first thing we're going to do here is we'll convert that into a one hot vector so there is a
method called one hot and what that method will do is it takes the review and then you specify your vocabulary size 
size so let's say if you say 30 it will give
a unique numbers so here it gives 3 number to amazing and 18 to restaurent so the number
will be between
1 to 30. 
If i say 500 the max number will be 500 basically here we get 304 and 127
so after one hot encoding we are getting a fixed unique number and internally keras that the layer will
convert it to 0 0 1 1 and so'''


In [4]:
one_hot("amazing restaurant",30)

[4, 17]

In [5]:
one_hot("amazing restaurant",500)

[235, 82]

In [ ]:
'''initialize vocabulary size let's say my vocab size is 30. Now i want to encode all these
 reviews as same i did for amazing restaurant,  for each review I created encoded vector'''

In [7]:
vocab_size = 30                                   
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[25, 18], [4, 17], [26, 24], [18, 26, 1], [9, 2, 23], [4, 18], [11, 2, 12], [24, 24], [24, 11], [22, 3]]


In [8]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post') #padding post means pair the reviews towards the end so now see towards the end I get zeros
print(padded_reviews)

[[25 18  0]
 [ 4 17  0]
 [26 24  0]
 [18 26  1]
 [ 9  2 23]
 [ 4 18  0]
 [11  2 12]
 [24 24  0]
 [24 11  0]
 [22  3  0]]


In [ ]:
'''my model is what like sequential okay and then i need to add my first layer so my first layer  will be embedding layer  
for that I have already imported embedding class and the way embedding class works is it takes a couple of argument okay so what 
is the first argument the first argument is vocab size then the second argument is the vector size my model is what like sequential okay 
and then i need to add my first layer so my first layer  will be embedding layer  for that I have already imported embedding class and the 
way embedding class works is it takes a couple of argument okay so what is the first argument the first argument
is vocab size then the second argument is the vector size so vocabulary size is 30 then my vector size after the vector size you will 
supply the length so max length is 3 and I need to give it a name so that I can use it later'''

In [10]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [ ]:
'''The second layer again if you look at the diagram once you get embedding vectors these vectors
from your embedding layer you want to
flatten them to create this particular vector 
the layer after that is one neuron sigmoid activation function so it will be a dense layer with a sigma activation
now just to make it more convenient my x is padded reviews and y sentiment correct
this is my x training samples and this is my labels y so just to make it easy I'm just putting them in a different variable called x and y
and I will now compile my model 


In [11]:
X = padded_reviews
y = sentiment


In [ ]:
'''usually we end up using adam as an optimizer and binary cross entropy because the output is either one
or zero right like the review is positive or negative that's why binary cross entropy
and then you can print when you run it see the embedding vector size is four the max sentence length is three all
right once you do flatten you will get twelve 12 '''


In [12]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten (Flatten)           (None, 12)                0         
                                                                 
 dense (Dense)               (None, 1)                 13        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________
None


In [13]:
model.fit(X, y, epochs=50, verbose=0)

In [14]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 107ms/step - loss: 0.6352 - accuracy: 0.9000


0.8999999761581421

In [15]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [16]:
weights[13]

array([-0.04224786, -0.0399904 ,  0.04945857,  0.02715309], dtype=float32)

In [17]:
weights[4]

array([-0.0024863 , -0.00578571, -0.06843247, -0.07322812], dtype=float32)

In [18]:
weights[16]

array([-0.04884008,  0.01270571, -0.04317185,  0.01137583], dtype=float32)